# Setup
markdown:            kramdown
highlighter:         Rouge
title:               lbwei
tagline:             'doodles'
description:         'Enjoy :)'
url:                 https://lbwei1016.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              lbwei
  url:               https://github.com/lbwei1016
  email:             0800680274united@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

# collections
collections_dir: my_collections
collections:
        Math:
          # label: Math
          url: "/Math"
          output: true
        Misc:
          # label: Misc
          output: true
                       
